version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: my_db
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 123
    ports:
      - "9906:3306"
    volumes:
      - ./src/mysql/:/var/lib/mysql/
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
