version: '3'

services:
  mysql:
    #restart: always
    #image: mysql:5.7
    build:
      context: .
      dockerfile: ./src/for_mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123
      #MYSQL_DATABASE: my_db
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    #volumes:
      #- ./src/mysql/:/var/lib/mysql/
      #- ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  
  web:
    #image: php:7.2.2-apache
    build:
      context: .
      dockerfile: ./src/for_php:apache
    
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
